### ISSUE TITLE
steps for how to use weave-wiper script in kubernetes cluster

### ISSUE THREAD

**Issue by kasim457** [ocadotechnology/weave-wiper#9]
Hi,

As I have been experiencing IP leakage issue in k8s 1.12.2 & 1.13.2 clusters very frequently. I found someone created a script called wiper.bash to release unused IP's in k8s. I did not find steps how to use it in order to release unused IPs.

I cloned the git clone https://github.com/ocadotechnology/weave-wiper.git and executed "sh wiper.bash". However, I ended up with below error message.

[root@ip-172-31-0-133 weave-wiper]# sh wiper.bash
wiper.bash: line 97: `T_ids_wrong_files_validation_containers-json': not a valid identifier
[root@ip-172-31-0-133 weave-wiper]#

Could you help me how to use it in kubernetes clsuter.

**Comment by stuart-warren** [comment]
Hi, this is a bash script, running with a different shell probably won't work though that is an odd error message

There is an upstream bug and related mr for the issue that this was written to work around (which it seems you have found 👍 )

https://github.com/weaveworks/weave/issues/3587

**Comment by stuart-warren** [comment]
we add an extra container to the [weave-net daemonset](https://github.com/weaveworks/weave/tree/master/prog/weave-kube) in Kubernetes
```
     - image: ocadotechnology/weave-wiper:0.1.3
       name: weave-wiper
       resources:
         requests:
           cpu: 100m
       volumeMounts:
       - mountPath: /host/run/docker.sock
         name: dockersock
```

**Comment by kasim457** [comment]
> 
> 
> we add an extra container to the [weave-net daemonset](https://github.com/weaveworks/weave/tree/master/prog/weave-kube) in Kubernetes
> 
> ```
>      - image: ocadotechnology/weave-wiper:0.1.3
>        name: weave-wiper
>        resources:
>          requests:
>            cpu: 100m
>        volumeMounts:
>        - mountPath: /host/run/docker.sock
>          name: dockersock
> ```

Do I need to add weave-wiper container spect to weave-net.yaml file which we used to deploy cni plugin in cluster ?

**Comment by stuart-warren** [comment]
I'm not sure how you deploy the cni plugin, this is the daemonset that runs the weave-npc/weave-kube containers. it may be the same thing?

**Comment by kasim457** [comment]
> 
> 
> I'm not sure how you deploy the cni plugin, this is the daemonset that runs the weave-npc/weave-kube containers. it may be the same thing?

Do I need to perform any action after deploying weave-wiper as daemonset ?

**Comment by stuart-warren** [comment]
not if logs appear fine

**Comment by kasim457** [comment]
> 
> 
> not if logs appear fine

Here is the entry which i added to my weave-net.yaml file.

 - name: weave-npc
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: 'weaveworks/weave-npc:2.5.0'
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
              volumeMounts:
                - name: xtables-lock
                  mountPath: /run/xtables.lock
            - name: weave-wiper
              image: ocadotechnology/weave-wiper:0.1.3
              resources:
                requests:
                  cpu: 100m
              volumeMounts:
                - mountPath: /host/run/docker.sock
                  name: dockersock


When I perform dry-run, it does not show error message. But, if I try to apply the changes, it says

[root@devcloud ~]# kubectl apply -f net.yaml
serviceaccount/weave-net unchanged
clusterrole.rbac.authorization.k8s.io/weave-net unchanged
clusterrolebinding.rbac.authorization.k8s.io/weave-net unchanged
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
The DaemonSet "weave-net" is invalid: spec.template.spec.containers[2].volumeMounts[0].name: Not found: "dockersock"

**Comment by stuart-warren** [comment]
you may need to create a volume pointing at your hosts docker socket file in that case

**Comment by kasim457** [comment]
> 
> 
> you may need to create a volume pointing at your hosts docker socket file in that case

you mean creating a directory structure on host level like /host/run folder

**Comment by stuart-warren** [comment]
no a hostpath volume similar to:

```
    volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock
```

**Comment by mikebryant** [comment]
The extra bits to add to the weave-net daemonset - this is not a standalone daemonset
```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
spec:
  template:
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: weave-wiper
        image: ocadotechnology/weave-wiper:0.1.5
        resources:
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /host/run/docker.sock
          name: dockersock
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersock

```
